# coding: utf-8

"""
    Transactions API

     The transactions API lets you view your transactions, accounts, and statements. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_transactions_python_sdk.paths.v2_accounts_cash_id.get import GetCashAccountRaw
from brex_transactions_python_sdk.paths.v2_accounts_card.get import ListCardAccountsRaw
from brex_transactions_python_sdk.paths.v2_accounts_cash.get import ListCashAccountsRaw
from brex_transactions_python_sdk.paths.v2_accounts_cash_id_statements.get import ListCashStatementsRaw
from brex_transactions_python_sdk.paths.v2_accounts_card_primary_statements.get import ListPrimaryCardStatementsRaw
from brex_transactions_python_sdk.paths.v2_accounts_cash_primary.get import StatusRaw


class AccountsApiRaw(
    GetCashAccountRaw,
    ListCardAccountsRaw,
    ListCashAccountsRaw,
    ListCashStatementsRaw,
    ListPrimaryCardStatementsRaw,
    StatusRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
