# coding: utf-8

"""
    Transactions API

     The transactions API lets you view your transactions, accounts, and statements. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_transactions_python_sdk.paths.v2_accounts_cash_id.get import GetCashAccount
from brex_transactions_python_sdk.paths.v2_accounts_card.get import ListCardAccounts
from brex_transactions_python_sdk.paths.v2_accounts_cash.get import ListCashAccounts
from brex_transactions_python_sdk.paths.v2_accounts_cash_id_statements.get import ListCashStatements
from brex_transactions_python_sdk.paths.v2_accounts_card_primary_statements.get import ListPrimaryCardStatements
from brex_transactions_python_sdk.paths.v2_accounts_cash_primary.get import Status
from brex_transactions_python_sdk.apis.tags.accounts_api_raw import AccountsApiRaw


class AccountsApi(
    GetCashAccount,
    ListCardAccounts,
    ListCashAccounts,
    ListCashStatements,
    ListPrimaryCardStatements,
    Status,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AccountsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AccountsApiRaw(api_client)
