# coding: utf-8

"""
    Transactions API

     The transactions API lets you view your transactions, accounts, and statements. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_transactions_python_sdk.paths.v2_transactions_card_primary.get import ListAllCardTransactionsRaw
from brex_transactions_python_sdk.paths.v2_transactions_cash_id.get import ListByIdRaw


class TransactionsApiRaw(
    ListAllCardTransactionsRaw,
    ListByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
