# coding: utf-8

"""
    Transactions API

     The transactions API lets you view your transactions, accounts, and statements. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_transactions_python_sdk.paths.v2_transactions_card_primary.get import ListAllCardTransactions
from brex_transactions_python_sdk.paths.v2_transactions_cash_id.get import ListById
from brex_transactions_python_sdk.apis.tags.transactions_api_raw import TransactionsApiRaw


class TransactionsApi(
    ListAllCardTransactions,
    ListById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TransactionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TransactionsApiRaw(api_client)
