# coding: utf-8

"""
    Transactions API

     The transactions API lets you view your transactions, accounts, and statements. 

    The version of the OpenAPI document: 1.0
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_transactions_python_sdk import schemas  # noqa: F401


class CardTransactionType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    
    @schemas.classproperty
    def PURCHASE(cls):
        return cls("PURCHASE")
    
    @schemas.classproperty
    def REFUND(cls):
        return cls("REFUND")
    
    @schemas.classproperty
    def CHARGEBACK(cls):
        return cls("CHARGEBACK")
    
    @schemas.classproperty
    def REWARDS_CREDIT(cls):
        return cls("REWARDS_CREDIT")
    
    @schemas.classproperty
    def COLLECTION(cls):
        return cls("COLLECTION")
    
    @schemas.classproperty
    def BNPL_FEE(cls):
        return cls("BNPL_FEE")
